name: Angular E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" , "main"]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM dependencies
        working-directory: marketplace-fe
        run: npm ci
        # Using npm ci for a clean, deterministic install (faster and more reliable in CI than npm install)&#8203;:contentReference[oaicite:4]{index=4}

      - name: Build Angular app (production)
        working-directory: marketplace-fe
        run: npm run build -- --configuration=production

      - name: Start Angular dev server
        working-directory: marketplace-fe
        run: npm run start -- --configuration=production &
        # Starts the dev server in the background on default port (e.g., 4200)

      - name: Wait for dev server to be ready
        run: npx wait-on http://localhost:4200
        # Wait until the Angular app is responding. For Node 18+/Ubuntu runners, you may need to target IPv6 localhost if necessary&#8203;:contentReference[oaicite:5]{index=5}.

      - name: Run Cypress E2E tests (Headless Chrome)
        working-directory: marketplace-fe
        run: npx ng e2e --configuration=production --headless --browser=chrome
        # Runs the Angular E2E tests with Cypress in headless Chrome. Fails if any test fails.
